### get all users
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/

### test
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/friends

#### add user
POST https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users
Content-Type: application/json

{
	"userName": "Monine",
	"userNameLoc": "Mochan",
	"firstName": "Peter",
	"lastName": "Parker",
	"is2Fa": false,
	"authToken": "ddddddss",
	"email": "billbissllisssnddddghhhhhton@rich.com",
	"secret2Fa" : "",
	"avatar" : "https://www.svgrepo.com/show/303599/spider-man-4-logo.svg",
	"xp": 123456,
	"isLogged": true,
	"lastSeen": "Hello"
}

###  Edit user info
PATCH  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/2
Content-Type: application/json

{
  "userName": "fakouyat",
  "userNameLoc": "kouyaBoss",
  "firstName": "Facinet",
  "lastName": "Kouyate",
  "is2Fa": false,
  "authToken": "dkdkd",
  "email": "fakouyat@student.42wolfsburg.de",
  "secret2Fa": "H4DHQUYSIY6XOJTP",
  "avatar": "https://cdn.intra.42.fr/users/19eaa22c691bc561cf527f09a094bbad/fakouyat.jpg",
  "xp": 0,
  "isLogged": true,
  "lastSeen": "2023-08-02T17:30:58.572Z"
}

### udpate 2FA option
PATCH   https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/2fa/30

###  delete user
DELETE  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/7

### get user stat
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/1/stats

### creat user stat
POST https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/1/stats
Content-Type: application/json

{
  "userId": 0,
  "wins": 0,
  "losses": 0,
  "draws": 0
}

### update user stat
PATCH https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/2/stats
Content-Type: application/json

{
  "wins": 0,
  "losses": 0,
  "draws": 0
}

### delete user stat
DELETE  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/1/stats

### get user achievement
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/2/achievements/

### add user achievement
POST https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/2/achievements/
Content-Type: application/json

{
	"goalId": 1,
	"createdAt": "24-07-2023"
}

### delete achievement
DELETE https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/1/achievements/

### Get all goals 
GET  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/

### add the first goal
POST  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/1
Content-Type: application/json

{
	"label": "WELCOME",
	"image": "https://www.svgrepo.com/show/398519/trophy.svg",
	"description": "Welcome on board!"
}
### add a new goal
POST  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/
Content-Type: application/json

{
	"label": "Beat that Bot",
	"image": "https://www.svgrepo.com/show/131148/robot.svg",
	"description": "Won against the Bot on easy"
}

### 2nd. goal
POST  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/
Content-Type: application/json

{
	"label": "Artificial what now?",
	"image": "https://www.svgrepo.com/show/235195/robot-ai.svg",
	"description": "Won against the Bot on medium"
}

### 3rd goal
POST  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/
Content-Type: application/json

{
	"label": "iRobot who?",
	"image": "https://www.svgrepo.com/show/134/robot.svg",
	"description": "Won against the Bot on hard"
}

### 4th. goal
POST  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/
Content-Type: application/json

{
	"label": "Terminator termniated",
	"image": "https://www.svgrepo.com/show/402624/robot-face.svg",
	"description": "Won against the Bot on very hard"
}

### 5th. goal
POST  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/
Content-Type: application/json

{
	"label": "Heisted Heistotron",
	"image": "https://www.svgrepo.com/show/145418/robot.svg",
	"description": "Won against the Bot on extreme"
}

#	"label": "WELCOME PONG",
#	"image": "https://www.svgrepo.com/show/398519/trophy.svg",
#	"description": "this is the new member gift"
# const label = ['Beat that Bot', 'Artificial what now?', 'iRobot who?', 'Terminator termniated', 'Heisted the Heistotron'];
# const description = ['Won against the Bot on easy', 'Won against the Bot on medium', 'Won against the Bot on hard', 'Won against the Bot on very hard', 'Won against the Bot on extreme'];
# const image = ['https://www.svgrepo.com/show/470680/robot-face.svg', 'https://www.svgrepo.com/show/235195/robot-ai.svg', 'https://www.svgrepo.com/show/134/robot.svg', 'https://www.svgrepo.com/show/402624/robot-face.svg', 'https://www.svgrepo.com/show/145418/robot.svg'];

### patch a goal
PATCH  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/2
Content-Type: application/json

{
	"label": "Beat that Bot",
	"image": "https://www.svgrepo.com/show/131148/robot.svg",
	"description": "Won against the Bot on easy"
}
	

### Delete a goal
DELETE https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/goals/1

### display all user's friends
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/friends

### add a friend request to a user
POST  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/friends
Content-Type: application/json

{
	"receiver": 9,
	"sender": 12,
	"relation": "PENDING",
	"createdAt": "27/07/2023"
}

### update friend relation
PATCH   https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/friends/24
Content-Type: application/json

{
	"receiver": 2,
	"sender": 9,
	"relation": "ACCEPTED",
	"createdAt": "27/07/2023"
}

### delete friendship
DELETE https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/friends/31

### aut
POST https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/auth
Content-Type: application/json

{
	"token": "ddskdsdddsds"
}

### Generate secrete for 2FA
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/auth/2fa/30

### Validate the secrete
POST https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/auth/2fa
Content-Type: application/json

{
	"token": "259641",
	"userId": "30"
}

### avatar
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/users/avatar/faci30682023382.jpg


### get all messages
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/chats

### send a message
POST https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/chats
Content-Type: application/json

{
	"author": "4",
	"message": "Hi Facinet",
	"type": "PRIVATE",
	"receiver": "9"
}

### Delete a message

DELETE  https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/chats/4
### get games
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/pong/games

### game making
GET https://special-dollop-r6jj956gq9xf5r9-5000.app.github.dev/gamequeue/12