### get all users
GET http://localhost:5000/pong/users/2

#### add user
POST http://localhost:5000/pong/users
Content-Type: application/json

{
	"userName": "JohnDoe",
	"userNameLoc": "johndoe",
	"firstName": "John",
	"lastName": "Doe",
	"is2Fa": false,
	"authToken": "dddddd",
	"email": "johndoe@gmail.com",
	"secret2Fa" : "",
	"avatar" : "https://www.svgrepo.com/show/384669/account-avatar-profile-user-13.svg",
	"xp": 26,
	"isLogged": true,
	"lastSeen": ""
}

###  Edit user info
PATCH  http://localhost:5000/pong/users/12
Content-Type: application/json

{
	"userName": "Alim",
	"userNameLoc": "alim",
	"firstName": "Philipp",
	"lastName": "Maxim",
	"is2Fa": false,
	"authToken": "dddddd",
	"email": "philissspp@gmail.com",
	"secret2Fa" : "",
	"avatar" : "avatar",
	"xp": 26,
	"isLogged": true,
	"lastSeen": ""
}


###  delete user
DELETE  http://localhost:5000/pong/users/12

### get user stat
GET http://localhost:5000/pong/users/2/stats

### creat user stat
POST http://localhost:5000/pong/users/2/stats
Content-Type: application/json

{
  "userId": 0,
  "wins": 0,
  "losses": 0,
  "draws": 0
}

### update user stat
PATCH http://localhost:5000/pong/users/1/stats
Content-Type: application/json

{
  "wins": 3,
  "losses": 0,
  "draws": 0
}

### delete user stat

DELETE  http://localhost:5000/pong/users/1/stats


### get user achievement
GET http://localhost:5000/pong/users/1/achievements/

### add user achievement
POST http://localhost:5000/pong/users/1/achievements/
Content-Type: application/json

{
	"label": "Welcome!",
	"description": "This achievement is created for your first login",
	"image": "https://www.svgrepo.com/show/398519/trophy.svg",
	"createdAt": "24-07-2023"
}

