import React from 'react'
import { Button } from '../ui/Button'
import { useNavigate } from 'react-router-dom'
import { useEffect, useState } from 'react';
import { encode } from 'hi-base32';
import QRCode from 'qrcode.react';
import OTPInput from 'react-otp-input';
import base32 from 'base32-encode';

//import speakeasy from 'speakeasy';
//import notp from 'notp';
//import queryString from "query-string"
import '../../css/login.css'

interface Props {
    is2faEnabled: boolean
    isAuth: boolean
	setIsAuth: React.Dispatch<React.SetStateAction<boolean>>
	setCode: React.Dispatch<React.SetStateAction<string | null>>

}




const Login2fa: React.FC<Props> = ({ setIsAuth, isAuth, is2faEnabled, setCode }) => {

    const [otp, setOTP] = useState<string>('');
    const [secret2FA, setSecret2FA] = useState<string>('');
    const navigate = useNavigate();


    // Generate new key for user
    const generateSecret = () =>
    {
        //const secret = notp.notp.genSecret(32);
    }


    const Utils_2faSetup = () => {
    var secret_2FA_demo = 'qerj34jFsdfqqfqmi437/=m#?jfav+vavacvadckv';   // to be generated by backend
    //var secret_2FA_demo = '123546'   // to be generated by backend
    //const [encodedSecret2fa, setEncodedSecret2fa ] = useState<string>('');
    const encodedSecret2fa = encode(secret_2FA_demo);                    // convert secret to base32
    setSecret2FA(encodedSecret2fa);                                      // contact backend for secret code;
    //const [secret, setSecret] = useState<string>('');
    //const [verified, setVerified] = useState<boolean>(false);

 
    }

    useEffect( () => {
        Utils_2faSetup();

    },[]
    )
	const handle2fa = () => 
    {
        console.log(secret2FA);
        console.log(otp)
        // send code to backend for verification
        if (otp === secret2FA)
        {
            setIsAuth(true);
            navigate('/');
        }
    }
  
	return (
        <div className='h-screen bg-gray-200 dark:bg-slate-900 w-full grid place-items-center'>
            <div > 
                <div className='login__form_item'>
                    <Button>
				        Scan QRCode
			        </Button>
                </div>
        		<div className='login__form_item'>
           		    <QRCode value={ secret2FA } /> 
                </div>

        		<div className='login__form_item input'>
                    <input
                        type="text"
                        value={otp}
                        onChange={(e) => setOTP(e.target.value)}
                        width={50}
                    />
        		</div>
                <div className='login__form_item'>
                    <Button
					    type='submit'
					    onClick={handle2fa}
				    >
					    validate
				    </Button>
                </div>
            </div>
        </div>
	)
}

export default Login2fa
